services:
  eth-fh:
    image: custometh/eth-firehose:v1.16.8-b
    labels:
      logging: "promtail"
      logging_jobname: "chain/execution"
      component: "eth-fh"
    container_name: eth-fh
    volumes:
      - ${PROJECT_ROOT_ETHEREUM}/chain/execution/config/eth-firehose-mainnet.yaml:/etc/firehose/config.yml:ro
      - eth_firehose_data:/app/firehose-data/storage
      - eth_blocks_data:/var/lib/firehose
    command: ["-c", "/etc/firehose/config.yml", "start"]
    ports:
      - "10015:10015" # Firehose grpc
    restart: unless-stopped
    networks:
      - eth-chain-net
    deploy:
      replicas: 1
    stop_grace_period: 300s

  lighthouse:
    image: sigp/lighthouse:v8.1.0
    labels:
      logging: "promtail"
      logging_jobname: "chain/consensus"
      component: "lighthouse"
      group: "chain"
      project: "grt"
    ports:
      - "15052:5052" # Lighthouse rpc
      - "9000:9000/tcp" # p2p
      - "9000:9000/udp" # p2p
    volumes:
      - lighthouse_data:/root/.lighthouse
      # - logs:/root/.lighthouse/mainnet/beacon/logs
      - ${PROJECT_ROOT_ETHEREUM}/chain/jwttoken:/root/jwt
    command: >
      lighthouse bn
      --network mainnet
      --http
      --http-address=0.0.0.0
      --http-port=5052
      --http-allow-origin=*
      --execution-endpoint=http://eth-fh:8551
      --execution-jwt=/root/jwt/jwt.hex
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=5054
      --checkpoint-sync-url=https://sync-mainnet.beaconcha.in
      --target-peers=50
      --port=9000
      --discovery-port=9000
      --enr-udp-port=9000
      --enr-tcp-port=9000
      --enr-address=${EXT_IP:-0.0.0.0}
      --supernode
      --blob-prune-margin-epochs 16384
    networks:
      - eth-chain-net
    deploy:
      replicas: 1
    stop_grace_period: 300s

networks:
  eth-chain-net:
    driver: overlay

volumes:
  eth_firehose_data:
    driver: local
    driver_opts:
      type: none
      device: ${ETH_FIREHOSE_DATA_PATH:-/mnt/chain/eth-fh-data}
      o: bind
  eth_blocks_data:
    driver: local
    driver_opts:
      type: none
      device: ${ETH_FIREHOSE_BLOCKS_DATA_PATH:-/mnt/chain/eth-fh}
      o: bind
  lighthouse_data:
    driver: local
    driver_opts:
      type: none
      device: ${CHAIN_LIGHTHOUSE_DATA_PATH:-/mnt/chain/eth-cl}
      o: bind
